# Generated by Django 5.0.9 on 2024-11-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaintapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comreg',
            table='compreg',
        ),
    ]
