# Generated by Django 5.0.9 on 2024-11-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaintapp', '0002_alter_comreg_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comreg',
            table='comreg',
        ),
    ]
