# Generated by Django 5.0.9 on 2024-11-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintapp', '0003_alter_comreg_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='compreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'compreg',
            },
        ),
        migrations.DeleteModel(
            name='comreg',
        ),
    ]
